sudo: required
branches:
  only: 
    - master
services:
  - docker

  before_install:
    - docker build -t cyeluri/udemy/docker-react-travis-ci:v1.0.0 Dockerfile.dev .

  script:
    - docker run   cyeluri/udemy/docker-react-travis-ci:v1.0.0 npm run test -- --coverage



