version: '3'
services:
  react-web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3000"
    volumes: 
      - /app/node_module
      - .:/app
  react-web-test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_module
      - .:/app  
    command: ["npm", "run", "test"]    